### ISSUE TITLE
Build failed with an exception 

### ISSUE THREAD

**Issue by bahman2000** [ekasetiawans/flutter_background_service#381]
I updated the package to version `5.0.3`. Now I am facing following error in this version and even in the previous versions.

`E:\Android_Studio\Projects\SampleProject\android\app\src\debug\AndroidManifest.xml Error:
	Attribute service#id.flutter.flutter_background_service.BackgroundService@foregroundServiceType at AndroidManifest.xml requires a placeholder substitution but no value for <foregroundServiceType> is provided.`

`* What went wrong:
Execution failed for task ':app:processDebugMainManifest'.
Manifest merger failed : Attribute service#id.flutter.flutter_background_service.BackgroundService@foregroundServiceType at AndroidManifest.xml requires a placeholder substitution but no value for <foregroundServiceType> is provided.`

**Comment by bahman2000** [comment]
I got this solved by doing the configuration for Foreground Services on Android 14 (view the documentation for more information)

**Comment by BehroozBvk** [comment]
I also proceeded according to the document, but the problem is still there
