### ISSUE TITLE
Background service does not start with flutter 3.29.0

### ISSUE THREAD

**Issue by xbug42** [ekasetiawans/flutter_background_service#506]
I recently upgraded to the latest flutter (3.29.0) and it looks like flutter_background_service is not working anymore on Android :
- startService() returns true
- no error trace anywhere
- the entry point is never called (defined in AndroidConfiguration.onStart)
- did not try yet on IOS
- work fine again with the same code after downgrading flutter to 3.27.4 

flutter_background_service: 5.1.0
flutter_background_service_android: 6.3.0
flutter_background_service_ios: 5.0.3
flutter_background_service_platform_interface: 5.1.2

**Comment by Mc231** [comment]
@xbug42 I encountered same issue, in logs I observed following:

`E/DartVM  ( 1646): ERROR: To access '.../initializers/service_initializer.dart::ServiceInitializer' from native code, it must be annotated.
E/DartVM  ( 1646): ERROR: See https://github.com/dart-lang/sdk/blob/master/runtime/docs/compiler/aot/entry_point_pragma.md
E/flutter ( 1646): [ERROR:flutter/lib/ui/dart_runtime_hooks.cc(38)] Dart Error: ERROR: To access '.../initializers/service_initializer.dart::ServiceInitializer' from native code, it must be annotated.`

I managed to solve it by adding  `@pragma('vm:entry-point')` to class 


 Code Before fix
```dart
class ServiceInitializer {

  Future<void> initialize(bool isForegroundMode) async {
    // ... Service configuration code
  }

  @pragma('vm:entry-point')
  static Future<bool> onIosBackground(ServiceInstance service) async {
    // ...
  }

  @pragma('vm:entry-point')
  static void onStart(ServiceInstance service) async {
    // ...
  }
}
```

Code after fix

```dart
@pragma('vm:entry-point')
class ServiceInitializer {

  Future<void> initialize(bool isForegroundMode) async {
    // ... Service configuration code
  }

  @pragma('vm:entry-point')
  static Future<bool> onIosBackground(ServiceInstance service) async {
    // ...
  }

  @pragma('vm:entry-point')
  static void onStart(ServiceInstance service) async {
    // ...
  }
}
```

So adding @pragma('vm:entry-point') to class solved it for me.

**Comment by aliumac** [comment]
I had same issue. Thanks to @Mc231  solved with class level pragmra

**Comment by rpekarek-tc** [comment]
Same issue on iOS, the provided fix works there as well

**Comment by abiyyu19** [comment]
After adding @pragma('vm:entry-point'), I'm still encountering this issue:

E/DartVM  ( 8279): ERROR: To access 'package:cbflutter/background_service.dart::BackgroundService' from native code, it must be annotated.
E/DartVM  ( 8279): ERROR: See https://github.com/dart-lang/sdk/blob/master/runtime/docs/compiler/aot/entry_point_pragma.md
E/flutter ( 8279): [ERROR:flutter/lib/ui/dart_runtime_hooks.cc(38)] Dart Error: ERROR: To access 'package:cbflutter/background_service.dart::BackgroundService' from native code, it must be annotated.
E/flutter ( 8279): ERROR: See https://github.com/dart-lang/sdk/blob/master/runtime/docs/compiler/aot/entry_point_pragma.md
E/flutter ( 8279): [ERROR:flutter/shell/common/shell.cc(115)] Dart Error: ERROR: To access 'package:cbflutter/background_service.dart::BackgroundService' from native code, it must be annotated.
E/flutter ( 8279): ERROR: See https://github.com/dart-lang/sdk/blob/master/runtime/docs/compiler/aot/entry_point_pragma.md
